### ISSUE TITLE
Specifying a newer Zend Server version

### ISSUE THREAD

**Issue by centrepiece** [zend-patterns/ZendServerBamboo#16]
I am currently using version 2018.0.1 of Zend Server. However, when this is used for the Deployment Task and Deployment Check Task, it results in an error which states than an invalid Zend Server version has been inputted. Is there any workaround for this? Thanks!

**Comment by slaff** [comment]
Did you try using the latest version of https://github.com/zend-patterns/ZendServerSDK ? You can download one from here: https://github.com/zend-patterns/ZendServerSDK/raw/master/bin/zs-client.phar

**Comment by centrepiece** [comment]
I used the latest version, but still encountered this error.

**Comment by centrepiece** [comment]
This was a mistake on my part. Found Zend Server version from ...\Zend\ZendServer\gui\config\zs_ui.ini and added this to task. All working now.
